### ISSUE TITLE
Sleep nights fetched from database on the Main thread

### ISSUE THREAD

**Issue by mario-paniccia** [udacity/andfun-kotlin-sleep-tracker#12]
When the SleepTrackerViewModel is created the list of sleep nights `nights` is retrieved from the DB without a coroutine and on the Main thread. Wouldn't this slow down the UI?
https://github.com/udacity/andfun-kotlin-sleep-tracker/blob/b48d6083c6374d45e681b2b740a3686163beb8b5/app/src/main/java/com/example/android/trackmysleepquality/sleeptracker/SleepTrackerViewModel.kt#L55

**Comment by bfahm** [comment]
I have the exact same question!

**Comment by mario-paniccia** [comment]
Later on in the course it is explained that Room Database ensure that the query returning LiveData is run on background thread.  
See Lesson 9, Excercise 9.
I think it would be better to mention this before though
