### ISSUE TITLE
No tests were found

### ISSUE THREAD

**Issue by crayonwriter** [udacity/andfun-kotlin-sleep-tracker#18]
I got the following error message when running the test:
Test running failed: Unable to find instrumentation info for: ComponentInfo{com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner}. onError: commandError=true message=INSTRUMENTATION_FAILED: com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner

Help!

**Comment by crayonwriter** [comment]
Testing started at 1:24 AM ...

09/13 01:24:43: Launching 'SleepDatabaseTest' on Pixel 2 API 28.
Running tests

$ adb shell am instrument -w -r    -e debug false -e class 'com.example.android.trackmysleepquality.SleepDatabaseTest' com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner

Started running tests

Test running failed: Unable to find instrumentation info for: ComponentInfo{com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner}. onError: commandError=true message=INSTRUMENTATION_FAILED: com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner
Tests ran to completion.

**Comment by crakaC** [comment]
I got same error and I added 
```testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"```
in defaultConfig braces at app build.gradle.
