### ISSUE TITLE
API 'BaseVariant.getApplicationIdTextResource' is obsolete

### ISSUE THREAD

**Issue by NitheshKumarK** [udacity/andfun-kotlin-sleep-tracker#20]
and I couldn't able to find the obsolete file

**Comment by danielvilha** [comment]
It looks like the 'androidx.navigation.safeargs' plugin in the build.gradle file uses getApplicationIdTextResource(), so it is more likely that the error message is caused by using this plugin.

**Comment by NitheshKumarK** [comment]
thank you so much
