### ISSUE TITLE
Test running failed: Unable to find instrumentation

### ISSUE THREAD

**Issue by claytonjwong** [udacity/andfun-kotlin-sleep-tracker#21]
Hi, in order to run the JUnit test for SleepDatabaseTest, I had to add the following line of code inside the app's build.gradle `android`, `defaultConfig`:

```
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
```

**Error Fixed:**

Testing started at 3:32 PM ...

11/03 15:32:28: Launching 'SleepDatabaseTest' on Pixel 3a API 30.
Running tests

$ adb shell am instrument -w -r    -e debug false -e class 'com.example.android.trackmysleepquality.SleepDatabaseTest' com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner

Started running tests

Test running failed: Unable to find instrumentation info for: ComponentInfo{com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner}. onError: commandError=true message=INSTRUMENTATION_FAILED: com.example.android.trackmysleepquality.test/android.test.InstrumentationTestRunner
Tests ran to completion.

**Comment by 220284hk** [comment]
Is there a fix on this? I downloaded the code and set the head to most recent and it still didn't work. 

Specifically, it is unhappy with the insertAndGetNight()
1. Suspend function 'getTonight' should be called only from a coroutine or another suspend function
and if I make it a suspend function 
2. java.lang.RuntimeException: Delegate runner 'androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner' for AndroidJUnit4 could not be loaded.

Note, this is after I added in the

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner" 

to the app gradle file.

**Comment by ejoon98** [comment]
I can't write English well, but recently I solved this problem by writing these sentences.

`testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"` 
First, add this in build.gradle(:app), android-defaultConfig

`testImplementation 'junit:junit:4.13'`
Second, modify junit version 4.12 to 4.13

press sync now, and I have big smile :)

Hope this help!!

**Comment by mir47** [comment]
There are two issues with the provided test setup, see my comment on a related issue [here](https://github.com/udacity/andfun-kotlin-sleep-tracker/issues/23#issuecomment-757372227)

**Comment by SudKul** [comment]
Closing out this issue, as it has been fixed in [this](https://github.com/udacity/andfun-kotlin-sleep-tracker/pull/24) PR. Thank you all. 👍
