### ISSUE TITLE
Error testing the database

### ISSUE THREAD

**Issue by MariemMezghani** [udacity/andfun-kotlin-sleep-tracker#23]
Hi, I am getting the following error when testing the database:

Suspend function 'insertAndGetNight' should be called only from a coroutine or another suspend function

**Comment by konflic** [comment]
Same here, even after fixing this tests wont run

**Comment by mir47** [comment]
The issue is `suspend` functions should be called from coroutine scope. For tests you can use a `runBlocking` block. Also `testInstrumentationRunner` should be added to build.gradle. I have submitted a pull request with a fix [here](https://github.com/udacity/andfun-kotlin-sleep-tracker/pull/24)

**Comment by Dannark** [comment]
@mir47 That pull request did fix my problem! Thanks bro!

**Comment by SudKul** [comment]
Closing out this issue, as it has been fixed in [this](https://github.com/udacity/andfun-kotlin-sleep-tracker/pull/24) PR. Thank you all. 👍
