### ISSUE TITLE
10. Testing the Room database

### ISSUE THREAD

**Issue by dev-lester94** [udacity/andfun-kotlin-sleep-tracker#31]
I uncomment the code and when I ran the test case it keeps saying that the test framework quit unexpectedly. Has to add the suspend keyword as it seems that you need to use a coroutine to insert and query the database. 

  @Test
    @Throws(Exception::class)
    suspend fun insertAndGetNight() {
        val night = SleepNight()
        sleepDao.insert(night)
        val tonight = sleepDao.getTonight()
        assertEquals(tonight?.sleepQuality, -1)
    }

**Comment by dev-lester94** [comment]
Looking at previous issues, I came up with a solution 
1. Add the following in defaultConfig in app gradle: testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
2. Wrap the code with runBlocking and not use suspend
 @Test
    @Throws(Exception::class)
    fun insertAndGetNight() {
        runBlocking {
            val night = SleepNight()
            sleepDao.insert(night)
            val tonight = sleepDao.getTonight()
            assertEquals(tonight?.sleepQuality, -1)
        }

    }

**Comment by DarkOhms** [comment]
Where was it suggested to use suspend?  I thought we were allowing queries on the main thread???
