### ISSUE TITLE
Why were the withContext(Dispatchers.IO) removed from the suspended functions on SleepTrackerViewModel

### ISSUE THREAD

**Issue by jpduran** [udacity/andfun-kotlin-sleep-tracker#32]
Commit [75ef93](https://github.com/udacity/andfun-kotlin-sleep-tracker/commit/945669f7fbb762e94c653114af7718831c75ef93)

**Comment by HasanElHefnawy** [comment]
In Commit [10723fd](https://github.com/udacity/andfun-kotlin-sleep-tracker/commit/10723fd0e828b21c399fcbb2e2653852bb22066a), `room-ktx` was added in app/build.gradle and `suspend` was added in SleepDatabaseDao.kt. The solution using `withContext` was before the following change in [Version 2.1.0](https://developer.android.com/jetpack/androidx/releases/room#2.1.0)
> Couroutines: DAO methods can now be suspend functions. Include room-ktx in your dependencies to take advantage of this functionality
