### ISSUE TITLE
Testing the room database - Test Failed

### ISSUE THREAD

**Issue by ghost** [udacity/andfun-kotlin-sleep-tracker#33]
I tried the following test function in my SleepDatabaseTest.kt:

```kotlin
@Test
@Throws(Exception::class)
fun updateAndGetNight() {
    val night = SleepNight()
    sleepDao.insert(night)
    val tonight = sleepDao.get(night.nightId)
    assertEquals(-1, tonight?.sleepQuality)
}
```

But something unexpected happened:
```logs
java.lang.AssertionError: expected:<-1> but was:<null>
```

Could you plz help me figure out what's wrong with my usage of the Dao function `get()`, or if not, where lies the problem?

**Comment by SudKul** [comment]
Hope that the recent [commit](https://github.com/udacity/andfun-kotlin-sleep-tracker/commit/98123508ddf59697a0c36994fa2c441079b52e1a#) will resolve this issue.
